# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19V5iCyoSd_pMEHGLP39xZVjbJEb8Dvh1
"""

"""Streamlit app for the Product Recommendation System.

Loads the model bundle created by product_recommendation.py and serves:
  1. Cluster-based recommendations for a user (KMeans / MiniBatchKMeans)
  2. Item-item similar products (cosine similarity)
  3. Popularity-based recommendations
"""

from pathlib import Path

import joblib
import pandas as pd
import streamlit as st

MODEL_PATH = Path(__file__).parent / "models" / "product_recommendation_models.joblib"
NEW_USER_LABEL = "New / Unknown User"

st.set_page_config(page_title="Product Recommendation System", layout="wide")

st.title("Product Recommendation System")
st.write("This app uses saved trained models for product recommendation.")

if not MODEL_PATH.exists():
    st.error(
        f"Model file not found: {MODEL_PATH}. Run product_recommendation.py and "
        "place the generated .joblib file inside the 'models' folder."
    )
    st.stop()


@st.cache_resource(show_spinner="Loading models...")
def load_resources(path: str):
    """Load the saved bundle once and prepare the item x user matrix."""
    bundle = joblib.load(path)
    # CSR layout makes slicing a single product row fast.
    item_user_matrix = bundle["user_item_matrix"].T.tocsr()
    return bundle, item_user_matrix


bundle, item_user_matrix = load_resources(str(MODEL_PATH))

cosine_model = bundle["cosine_model"]
user_ids = bundle["user_ids"]
product_ids = bundle["product_ids"]
product_to_idx = bundle["product_to_idx"]
global_top_products = bundle["global_top_products"]
popular_products = bundle["popular_products"]
seen_by_user = bundle["seen_by_user"]

CLUSTER_ARTIFACTS = {
    "KMeans": (
        bundle["kmeans_user_cluster_map"],
        bundle["kmeans_cluster_top_products"],
    ),
    "MiniBatchKMeans": (
        bundle["minibatch_user_cluster_map"],
        bundle["minibatch_cluster_top_products"],
    ),
}


def recommend_for_user(user_id, model_name="KMeans", top_n=10):
    """Return (cluster, recommended product ids) for a user."""
    user_cluster_map, cluster_top_products = CLUSTER_ARTIFACTS[model_name]
    already_seen = seen_by_user.get(user_id, set())

    if user_id in user_cluster_map:
        cluster = user_cluster_map[user_id]
        candidates = cluster_top_products.get(cluster, [])
    else:
        cluster = NEW_USER_LABEL
        candidates = []

    recommendations = [p for p in candidates if p not in already_seen][:top_n]

    # Top up with globally popular products (also covers new users).
    if len(recommendations) < top_n:
        fallback = [
            p for p in global_top_products
            if p not in recommendations and p not in already_seen
        ]
        recommendations += fallback[: top_n - len(recommendations)]

    return cluster, recommendations


def recommend_similar_products(product_id, top_n=10):
    """Return the top_n products most similar to product_id (cosine similarity)."""
    if product_id not in product_to_idx:
        return pd.DataFrame(columns=["productid", "similarity_score"])

    product_index = product_to_idx[product_id]
    n_neighbors = min(top_n + 1, len(product_ids))

    distances, indices = cosine_model.kneighbors(
        item_user_matrix[product_index], n_neighbors=n_neighbors
    )
    indices = indices.flatten()
    scores = 1 - distances.flatten()

    keep = indices != product_index  # drop the query product itself
    indices, scores = indices[keep][:top_n], scores[keep][:top_n]

    return pd.DataFrame(
        {"productid": product_ids[indices], "similarity_score": scores.round(4)}
    )


def get_popular_products(top_n=10):
    return popular_products.head(top_n).reset_index(drop=True)


# ----------------------------- Sidebar -----------------------------
st.sidebar.header("Settings")

model_choice = st.sidebar.selectbox("Choose clustering model", list(CLUSTER_ARTIFACTS))
top_n = st.sidebar.slider("Number of recommendations", min_value=5, max_value=20, value=10)

# ------------------------------ Tabs ------------------------------
tab1, tab2, tab3 = st.tabs(
    ["User Recommendations", "Similar Products", "Popular Products"]
)

with tab1:
    st.subheader("User-Based Product Recommendations")

    user_id_input = st.text_input("Enter User ID", value=str(user_ids[0])).strip()

    if st.button("Recommend Products for User"):
        cluster, recommendations = recommend_for_user(
            user_id_input, model_name=model_choice, top_n=top_n
        )

        st.write("Selected Model:", model_choice)
        st.write("User Cluster:", cluster)

        if isinstance(cluster, str):
            st.info("This user is not in the training data, so popular products are shown.")

        recommendation_df = pd.DataFrame({"recommended_productid": recommendations})
        recommendation_df.index = range(1, len(recommendation_df) + 1)
        st.dataframe(recommendation_df)

with tab2:
    st.subheader("Cosine Similarity Product Recommendations")

    product_id_input = st.text_input("Enter Product ID", value=str(product_ids[0])).strip()

    if st.button("Find Similar Products"):
        similar_products = recommend_similar_products(product_id_input, top_n=top_n)

        if similar_products.empty:
            st.warning("Product ID not found.")
        else:
            st.dataframe(similar_products, hide_index=True)

with tab3:
    st.subheader("Popularity-Based Recommendations")
    st.dataframe(get_popular_products(top_n), hide_index=True)