# -*- coding: utf-8 -*-
"""prod_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tp_H2A6Md-llnteNqCAszyfL1lvvrLo-
"""

"""
Product Recommendation System - training pipeline
=================================================
Data   : ratings.csv (no header) -> userid, productid, ratings, timestamp
Models : popularity baseline, item-item CF (cosine similarity), and user
         clustering on SVD embeddings (KMeans, MiniBatchKMeans, DBSCAN,
         Agglomerative)
Output : models/product_recommendation_models.joblib  (loaded by app.py)
"""

import os
import time

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.sparse import csr_matrix
from sklearn.cluster import DBSCAN, AgglomerativeClustering, KMeans, MiniBatchKMeans
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import davies_bouldin_score, silhouette_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import normalize

# ----------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------
MIN_USER_RATINGS = 5        # users with fewer ratings are dropped
MIN_PRODUCT_RATINGS = 10    # products with fewer ratings are dropped
MIN_POPULAR_RATINGS = 50    # minimum ratings for the popularity baseline
N_COMPONENTS = 50           # TruncatedSVD components
N_CLUSTERS = 5
TOP_N_PER_CLUSTER = 50
RANDOM_STATE = 42

MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "product_recommendation_models.joblib")

try:  # running inside Google Colab?
    from google.colab import drive, files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    drive.mount("/content/drive")
    DATA_PATH = "/content/drive/MyDrive/ratings.csv"
else:
    DATA_PATH = "ratings.csv"


# ----------------------------------------------------------------------
# Plot helpers
# ----------------------------------------------------------------------
def bar_with_labels(x, y, title, xlabel, ylabel, label_fmt="{:,.0f}",
                    color="skyblue", figsize=(8, 5), rotate=0):
    """Bar chart with a value label on every bar."""
    plt.figure(figsize=figsize)
    ax = sns.barplot(x=x, y=y, color=color)
    ax.set(title=title, xlabel=xlabel, ylabel=ylabel)
    for container in ax.containers:
        ax.bar_label(
            container,
            labels=[label_fmt.format(bar.get_height()) for bar in container],
            padding=3,
        )
    plt.xticks(rotation=rotate)
    plt.show()


def plot_sparse_heatmap(data, title):
    """Blue cell = user rated the product, white cell = not rated."""
    top_users = data["userid"].value_counts().head(30).index
    top_products = data["productid"].value_counts().head(30).index
    small = data[data["userid"].isin(top_users) & data["productid"].isin(top_products)]
    matrix = small.pivot_table(index="userid", columns="productid", values="ratings")

    plt.figure(figsize=(12, 7))
    sns.heatmap(matrix.notnull(), cmap="Blues", cbar=False, linewidths=0.5)
    plt.title(title)
    plt.xlabel("Product ID")
    plt.ylabel("User ID")
    plt.show()


# ----------------------------------------------------------------------
# 1. Load data
# ----------------------------------------------------------------------
# IDs are read as text so they match what is typed into the Streamlit app.
df = pd.read_csv(
    DATA_PATH,
    header=None,  # the file has no header row
    names=["userid", "productid", "ratings", "timestamp"],
    dtype={"userid": str, "productid": str},
)

print("Overall info of the dataset")
print("---------------------------")
df.info()
print(df.head())

print("\nNull values per column:")
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate (user, product) pairs:", df.duplicated(["userid", "productid"]).sum())

# The timestamp is not needed. A user should have one rating per product:
# csr_matrix SUMS duplicate (row, col) entries, which would inflate ratings,
# so keep only the last occurrence of each pair.
df = (
    df.drop(columns="timestamp")
    .drop_duplicates(["userid", "productid"], keep="last")
    .reset_index(drop=True)
)

print("\nUnique users:", df["userid"].nunique())
print("Unique products:", df["productid"].nunique())
print("Overall shape:", df.shape)
print(df.describe())

# ----------------------------------------------------------------------
# 2. EDA
# ----------------------------------------------------------------------
rating_counts = df["ratings"].value_counts().sort_index()
print("\nRating distribution:\n", rating_counts)
bar_with_labels(
    rating_counts.index, rating_counts.values, "Rating Distribution",
    "Ratings", "Number of Ratings", figsize=(6, 4),
)

top_products = df["productid"].value_counts().head(10)
print("\nTop 10 most rated products:\n", top_products)
bar_with_labels(
    top_products.index, top_products.values, "Top 10 Most Rated Products",
    "Product ID", "No. of ratings", figsize=(6, 4), rotate=45,
)

top_users = df["userid"].value_counts().head(10)
print("\nTop 10 users by number of ratings:\n", top_users)
bar_with_labels(
    top_users.index, top_users.values, "Top 10 Users by Number of Ratings",
    "User ID", "No. of ratings", figsize=(6, 4), rotate=45,
)

ratings_per_user = df.groupby("userid")["ratings"].count()
ratings_per_product = df.groupby("productid")["ratings"].count()
print("\nRatings per user summary:\n", ratings_per_user.describe().round(2))
print("\nRatings per product summary:\n", ratings_per_product.describe().round(2))

# Data sparsity = share of user-product cells with no rating.
n_users = df["userid"].nunique()
n_products = df["productid"].nunique()
total_cells = n_users * n_products
sparsity = (1 - len(df) / total_cells) * 100

print(f"\nUser-item matrix would be {n_users:,} x {n_products:,} = {total_cells:,} cells")
print(f"Only {len(df):,} are filled -> {sparsity:.4f}% sparse")
print(f"Users with exactly 1 rating: {(ratings_per_user == 1).sum():,} "
      f"({(ratings_per_user == 1).mean() * 100:.1f}%)")
print(f"Products with exactly 1 rating: {(ratings_per_product == 1).sum():,} "
      f"({(ratings_per_product == 1).mean() * 100:.1f}%)")

plot_sparse_heatmap(df, "Sparse User-Product Matrix (raw data)")


# ----------------------------------------------------------------------
# 3. Filter active users / products
# ----------------------------------------------------------------------
def filter_min_ratings(data, min_user_ratings, min_product_ratings, max_rounds=5):
    """Iteratively drop users/products below the rating thresholds.

    Iteration is needed because removing sparse products can push a user
    below the threshold (and vice versa). It is capped at `max_rounds`
    because running to full convergence keeps shrinking the data with
    rapidly diminishing returns.
    """
    d = data.copy()
    for i in range(1, max_rounds + 1):
        user_counts = d["userid"].value_counts()
        product_counts = d["productid"].value_counts()
        keep_users = user_counts[user_counts >= min_user_ratings].index
        keep_products = product_counts[product_counts >= min_product_ratings].index

        before = len(d)
        d = d[d["userid"].isin(keep_users) & d["productid"].isin(keep_products)]
        print(f"  round {i}: {before:,} -> {len(d):,} ratings | "
              f"{d['userid'].nunique():,} users | {d['productid'].nunique():,} products")
        if len(d) == before:
            print("  converged")
            break
    return d.reset_index(drop=True)


print(f"\nFiltering to users with >= {MIN_USER_RATINGS} and "
      f"products with >= {MIN_PRODUCT_RATINGS} ratings:")
df_filtered = filter_min_ratings(df, MIN_USER_RATINGS, MIN_PRODUCT_RATINGS)
print(f"Retained {len(df_filtered):,} of {len(df):,} ratings "
      f"({len(df_filtered) / len(df) * 100:.1f}%)")

plot_sparse_heatmap(df_filtered, "Sparse User-Product Matrix (filtered data)")


# ----------------------------------------------------------------------
# 4. User-item matrix (ML models need numeric indices, not text IDs)
# ----------------------------------------------------------------------
def build_sparse_matrix(data):
    """CSR user x product ratings matrix plus id <-> index lookups."""
    user_ids = data["userid"].unique()
    product_ids = data["productid"].unique()
    user_to_idx = {u: i for i, u in enumerate(user_ids)}
    product_to_idx = {p: i for i, p in enumerate(product_ids)}

    rows = data["userid"].map(user_to_idx).to_numpy()
    cols = data["productid"].map(product_to_idx).to_numpy()
    matrix = csr_matrix(
        (data["ratings"].to_numpy(), (rows, cols)),
        shape=(len(user_ids), len(product_ids)),
    )
    return matrix, user_to_idx, product_to_idx, user_ids, product_ids


user_item_matrix, user_to_idx, product_to_idx, user_ids, product_ids = (
    build_sparse_matrix(df_filtered)
)
density = user_item_matrix.nnz / (user_item_matrix.shape[0] * user_item_matrix.shape[1])
print(f"\nMatrix shape: {user_item_matrix.shape} | "
      f"non-zero entries: {user_item_matrix.nnz:,} | density: {density * 100:.3f}%")

# ----------------------------------------------------------------------
# 5. Popularity-based baseline (not personalized, useful for new users)
# ----------------------------------------------------------------------
popular_products = (
    df_filtered.groupby("productid")
    .agg(average_rating=("ratings", "mean"), rating_count=("ratings", "count"))
    .reset_index()
)
popular_products = (
    popular_products[popular_products["rating_count"] >= MIN_POPULAR_RATINGS]
    .sort_values(["average_rating", "rating_count"], ascending=False)
    .reset_index(drop=True)
)
print("\nTop popular products:\n", popular_products.head(10))

# ----------------------------------------------------------------------
# 6. Item-item collaborative filtering (cosine similarity)
# ----------------------------------------------------------------------
# Fitted on the FINAL matrix (products x users) so its indices match
# product_ids / product_to_idx saved in the bundle.
item_user_matrix = user_item_matrix.T.tocsr()
item_model = NearestNeighbors(metric="cosine", algorithm="brute")
item_model.fit(item_user_matrix)


def recommend_similar_products(product_id, n=5):
    """Return the n products most similar to product_id."""
    if product_id not in product_to_idx:
        return pd.DataFrame(columns=["productid", "similarity_score"])

    product_index = product_to_idx[product_id]
    distances, indices = item_model.kneighbors(
        item_user_matrix[product_index],
        n_neighbors=min(n + 1, len(product_ids)),
    )
    indices = indices.flatten()
    scores = 1 - distances.flatten()

    keep = indices != product_index  # drop the query product itself
    indices, scores = indices[keep][:n], scores[keep][:n]

    return pd.DataFrame({"productid": product_ids[indices], "similarity_score": scores})


sample_product = product_ids[0]
print(f"\nSelected product: {sample_product}")
similar_products = recommend_similar_products(sample_product, 10)
print(similar_products)

plt.figure(figsize=(10, 6))
ax = sns.barplot(data=similar_products, x="similarity_score", y="productid", color="skyblue")
ax.set(
    title=f"Cosine Similarity Products for Product {sample_product}",
    xlabel="Cosine Similarity Score",
    ylabel="Recommended Product ID",
    xlim=(0, 1),
)
for container in ax.containers:
    ax.bar_label(container, fmt="%.2f", padding=3)
plt.show()

# ----------------------------------------------------------------------
# 7. Dimensionality reduction (TruncatedSVD on the user-item matrix)
# ----------------------------------------------------------------------
svd_model = TruncatedSVD(n_components=N_COMPONENTS, random_state=RANDOM_STATE)
user_embeddings = svd_model.fit_transform(user_item_matrix)
print(f"\nEmbeddings shape: {user_embeddings.shape}")
print(f"Variance explained by {N_COMPONENTS} components: "
      f"{svd_model.explained_variance_ratio_.sum() * 100:.1f}%")

# ----------------------------------------------------------------------
# 8. User clustering
# ----------------------------------------------------------------------
def score_clusters(X, labels):
    """Silhouette (higher = better) and Davies-Bouldin (lower = better)."""
    silhouette = silhouette_score(X, labels, sample_size=5000, random_state=RANDOM_STATE)
    return silhouette, davies_bouldin_score(X, labels)


# Elbow method (MiniBatchKMeans is used only for speed while scanning k).
k_range = range(2, 11)
inertias = [
    MiniBatchKMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=5,
                    batch_size=1024).fit(user_embeddings).inertia_
    for k in k_range
]
fig, ax = plt.subplots(figsize=(6, 4))
ax.plot(list(k_range), inertias, marker="o")
ax.set(xlabel="k (number of clusters)", ylabel="Inertia (within-cluster sum of squares)",
       title="Elbow method for choosing k")
plt.tight_layout()
plt.show()

# --- KMeans -----------------------------------------------------------
t0 = time.time()
kmeans_model = KMeans(n_clusters=N_CLUSTERS, random_state=RANDOM_STATE, n_init=10)
kmeans_labels = kmeans_model.fit_predict(user_embeddings)
kmeans_fit_time = time.time() - t0
kmeans_silhouette, kmeans_db = score_clusters(user_embeddings, kmeans_labels)

print("\nKMeans cluster sizes:", np.bincount(kmeans_labels))
print(f"Silhouette score:     {kmeans_silhouette:.4f}  (higher = better separated)")
print(f"Davies-Bouldin index: {kmeans_db:.4f}  (lower = better separated)")

kmeans_counts = pd.Series(kmeans_labels).value_counts().sort_index()
bar_with_labels(kmeans_counts.index, kmeans_counts.values,
                "Number of Users in Each KMeans Cluster", "Cluster Number", "Number of Users")

# --- MiniBatchKMeans (faster, approximate) ----------------------------
t0 = time.time()
mbkmeans_model = MiniBatchKMeans(n_clusters=N_CLUSTERS, random_state=RANDOM_STATE,
                                 n_init=10, batch_size=1024)
mbkmeans_labels = mbkmeans_model.fit_predict(user_embeddings)
mbkmeans_fit_time = time.time() - t0
mbkmeans_silhouette, mbkmeans_db = score_clusters(user_embeddings, mbkmeans_labels)

print("\nMiniBatchKMeans cluster sizes:", np.bincount(mbkmeans_labels))
print(f"Silhouette score:     {mbkmeans_silhouette:.4f}")
print(f"Davies-Bouldin index: {mbkmeans_db:.4f}")
print(f"Fit time - KMeans:          {kmeans_fit_time * 1000:.1f} ms")
print(f"Fit time - MiniBatchKMeans: {mbkmeans_fit_time * 1000:.1f} ms")

mbk_counts = pd.Series(mbkmeans_labels).value_counts().sort_index()
bar_with_labels(mbk_counts.index, mbk_counts.values,
                "Number of Users in Each MiniBatchKMeans Cluster", "Cluster Number", "Number of Users")

# --- DBSCAN (noise points get label -1) -------------------------------
X_norm = normalize(user_embeddings.astype("float32"))
dbscan_labels = DBSCAN(eps=0.35, min_samples=10, metric="euclidean").fit_predict(X_norm)

n_dbscan_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise = int((dbscan_labels == -1).sum())
print(f"\nDBSCAN found {n_dbscan_clusters} clusters, {n_noise:,} noise points "
      f"({n_noise / len(dbscan_labels) * 100:.1f}% of users)")

# Defaults keep later tables valid even when DBSCAN cannot be scored.
dbscan_silhouette = dbscan_db = np.nan
clustered_idx = np.flatnonzero(dbscan_labels != -1)
if n_dbscan_clusters >= 2:
    rng = np.random.default_rng(RANDOM_STATE)
    score_idx = rng.choice(clustered_idx, size=min(5000, len(clustered_idx)), replace=False)
    sample_labels = dbscan_labels[score_idx]
    if len(np.unique(sample_labels)) >= 2:
        dbscan_silhouette = silhouette_score(X_norm[score_idx], sample_labels)
        dbscan_db = davies_bouldin_score(X_norm[score_idx], sample_labels)
        print(f"Silhouette score excluding noise:     {dbscan_silhouette:.4f}")
        print(f"Davies-Bouldin index excluding noise: {dbscan_db:.4f}")
else:
    print("Not enough non-noise clusters to compute silhouette / Davies-Bouldin.")

dbscan_counts = pd.Series(dbscan_labels).value_counts().sort_index()
bar_with_labels(dbscan_counts.index.astype(str), dbscan_counts.values,
                "Number of Users in Each DBSCAN Cluster",
                "Cluster Label (-1 means Noise)", "Number of Users",
                color="salmon", figsize=(10, 5))

# --- Agglomerative (O(n^2) memory, so scored on a random user sample) -
# Same embedding space, k and metrics as KMeans, but a different sample size,
# so the scores are not strictly comparable with the full-data KMeans scores.
rng = np.random.default_rng(RANDOM_STATE)
sample_idx = rng.choice(len(user_embeddings), size=min(3000, len(user_embeddings)), replace=False)
embeddings_sample = user_embeddings[sample_idx]

agglo_labels = AgglomerativeClustering(n_clusters=N_CLUSTERS).fit_predict(embeddings_sample)
agglo_silhouette = silhouette_score(embeddings_sample, agglo_labels)
agglo_db = davies_bouldin_score(embeddings_sample, agglo_labels)

print(f"\nAgglomerative cluster sizes ({len(embeddings_sample):,}-user sample):",
      np.bincount(agglo_labels))
print(f"Silhouette score:     {agglo_silhouette:.4f}")
print(f"Davies-Bouldin index: {agglo_db:.4f}")

# --- Comparison -------------------------------------------------------
clustering_comparison = pd.DataFrame({
    "Model": ["KMeans", "MiniBatchKMeans", "DBSCAN", "Agglomerative"],
    "Silhouette (higher=better)": [kmeans_silhouette, mbkmeans_silhouette,
                                   dbscan_silhouette, agglo_silhouette],
    "Davies-Bouldin (lower=better)": [kmeans_db, mbkmeans_db, dbscan_db, agglo_db],
    "N clusters": [N_CLUSTERS, N_CLUSTERS, n_dbscan_clusters, N_CLUSTERS],
    "Unassigned users": [0, 0, n_noise, 0],
    "Scales to full user base?": ["Yes", "Yes", "Yes", "Partially"],
})
print("\nClustering comparison:")
print(clustering_comparison.round(4).to_string(index=False))

bar_with_labels(clustering_comparison["Model"], clustering_comparison["Silhouette (higher=better)"],
                "Silhouette Score Comparison", "Clustering Model", "Silhouette Score",
                label_fmt="{:.4f}", figsize=(7, 5))
bar_with_labels(clustering_comparison["Model"], clustering_comparison["Davies-Bouldin (lower=better)"],
                "Davies-Bouldin Score Comparison", "Clustering Model", "Davies-Bouldin Score",
                label_fmt="{:.4f}", color="orange", figsize=(7, 5))

# ----------------------------------------------------------------------
# 9. Cluster-based recommendations
# ----------------------------------------------------------------------
def build_cluster_top_products(data, user_cluster_map, top_n=TOP_N_PER_CLUSTER):
    """Top products per user cluster, ranked by mean rating * log(1 + count)."""
    d = data.assign(cluster=data["userid"].map(user_cluster_map))
    stats = d.groupby(["cluster", "productid"])["ratings"].agg(["mean", "count"]).reset_index()
    stats["score"] = stats["mean"] * np.log1p(stats["count"])
    return {
        int(cluster): group.nlargest(top_n, "score")["productid"].tolist()
        for cluster, group in stats.groupby("cluster")
    }


def build_global_top_products(data, top_n=TOP_N_PER_CLUSTER):
    """Global fallback list for cold-start users, same scoring as above."""
    stats = data.groupby("productid")["ratings"].agg(["mean", "count"]).reset_index()
    stats["score"] = stats["mean"] * np.log1p(stats["count"])
    return stats.nlargest(top_n, "score")["productid"].tolist()


kmeans_user_cluster_map = {u: int(c) for u, c in zip(user_ids, kmeans_labels)}
mbkmeans_user_cluster_map = {u: int(c) for u, c in zip(user_ids, mbkmeans_labels)}

kmeans_cluster_top_products = build_cluster_top_products(df_filtered, kmeans_user_cluster_map)
mbkmeans_cluster_top_products = build_cluster_top_products(df_filtered, mbkmeans_user_cluster_map)
global_top_products = build_global_top_products(df_filtered)
seen_by_user = df_filtered.groupby("userid")["productid"].apply(set).to_dict()

print(f"\nBuilt per-cluster popularity lists for {len(kmeans_cluster_top_products)} clusters")
print(f"Global fallback list: {len(global_top_products)} products")


def recommend_for_user(user_id, user_cluster_map, cluster_top_products, k=10):
    """Top-k products for a user, excluding products they already rated."""
    already_seen = seen_by_user.get(user_id, set())

    if user_id in user_cluster_map:
        cluster = user_cluster_map[user_id]
        candidates = cluster_top_products.get(cluster, [])
    else:
        cluster = "New / Unknown User"  # user fell below the min-ratings filter
        candidates = []

    recs = [p for p in candidates if p not in already_seen][:k]

    # Cold-start / not-enough-candidates fallback: top up with global popularity.
    if len(recs) < k:
        backfill = [p for p in global_top_products if p not in recs and p not in already_seen]
        recs += backfill[: k - len(recs)]

    return cluster, recs


demo_user = user_ids[0]
demo_cluster, demo_recs = recommend_for_user(
    demo_user, kmeans_user_cluster_map, kmeans_cluster_top_products, k=10
)
print(f"\nUser: {demo_user} | cluster: {demo_cluster}")
print(f"Already rated {len(seen_by_user[demo_user])} products")
print(f"Top 10 recommendations: {demo_recs}")

# ----------------------------------------------------------------------
# 10. Model overview and recommender evaluation
# ----------------------------------------------------------------------
model_overview = pd.DataFrame({
    "Model": [
        "Popularity-Based Recommendation",
        "Item-Item Collaborative Filtering",
        "KMeans Clustering",
        "MiniBatchKMeans Clustering",
        "Agglomerative Clustering",
    ],
    "Purpose": [
        "Recommend generally popular products",
        "Recommend products similar to a selected product",
        "Group users with similar rating behaviour",
        "Group users faster for large data",
        "Group users step by step by merging the closest ones",
    ],
    "Personalized": ["No", "Yes", "Partially", "Partially", "Partially"],
    "Evaluation": [
        "Average rating and rating count",
        "Cosine similarity",
        "Silhouette and Davies-Bouldin score",
        "Silhouette and Davies-Bouldin score",
        "Silhouette and Davies-Bouldin score",
    ],
    "Advantage": [
        "Simple and fast",
        "Gives similarity-based recommendations",
        "Easy to understand clusters",
        "Better for large datasets",
        "Shows hierarchical relationship between clusters",
    ],
    "Limitation": [
        "Same recommendations for everyone",
        "Needs enough rating history",
        "Slower on large data",
        "Approximate clustering",
        "Slow and memory-heavy for large datasets",
    ],
})
print("\nModel overview:")
print(model_overview.to_string(index=False))

recommendation_eval_df = pd.DataFrame([
    {
        "Model": "Popularity-Based Recommendation",
        "Evaluation Metric": "Average rating and rating count",
        "Value 1": round(popular_products["average_rating"].head(10).mean(), 4),
        "Value 2": round(popular_products["rating_count"].head(10).mean(), 2),
    },
    {
        "Model": "Item-Item Collaborative Filtering",
        "Evaluation Metric": "Cosine similarity (average / highest)",
        "Value 1": round(similar_products["similarity_score"].mean(), 4),
        "Value 2": round(similar_products["similarity_score"].max(), 4),
    },
])
print("\nRecommendation evaluation:")
print(recommendation_eval_df.to_string(index=False))

# ----------------------------------------------------------------------
# 11. Save the model bundle used by app.py
# ----------------------------------------------------------------------
os.makedirs(MODEL_DIR, exist_ok=True)

model_bundle = {
    "kmeans_model": kmeans_model,
    "minibatch_kmeans_model": mbkmeans_model,
    "svd_model": svd_model,
    "cosine_model": item_model,
    "user_item_matrix": user_item_matrix,
    "user_ids": user_ids,
    "product_ids": product_ids,
    "user_to_idx": user_to_idx,
    "product_to_idx": product_to_idx,
    "kmeans_labels": kmeans_labels,
    "minibatch_labels": mbkmeans_labels,
    "kmeans_user_cluster_map": kmeans_user_cluster_map,
    "minibatch_user_cluster_map": mbkmeans_user_cluster_map,
    "kmeans_cluster_top_products": kmeans_cluster_top_products,
    "minibatch_cluster_top_products": mbkmeans_cluster_top_products,
    "global_top_products": global_top_products,
    "seen_by_user": seen_by_user,
    "popular_products": popular_products,
}

joblib.dump(model_bundle, MODEL_PATH, compress=3)
print(f"\nModel bundle saved to: {MODEL_PATH}")

# Sanity check: reload and confirm the saved cosine model matches the saved matrix.
loaded = joblib.load(MODEL_PATH)
assert loaded["cosine_model"].n_features_in_ == loaded["user_item_matrix"].shape[0]
assert loaded["cosine_model"].n_samples_fit_ == len(loaded["product_ids"])
print("Bundle reloaded successfully. Keys:", list(loaded.keys()))

if IN_COLAB:
    files.download(MODEL_PATH)

